# 자동심기 아이템의 설명(Lore)에 시간정보를 넣고싶으면 %time% 변수로 추가가능함.

AutoSeedON: '자동심기가 켜졌습니다.'
AutoSeedOFF: '자동심기가 꺼졌습니다.'
NoTime: '자동심기 시간이 부족합니다.'

# PlaceHolder 사용가능(ex, %player's displayname%), 시간 변수는 %current_time%
CurrentTime: '%current_time%초'

# PlaceHolder 사용가능(ex, %player's displayname%), 시간 변수는 %added_time%
TimeAdded: '%added_time% 초만큼 추가되었습니다.'

# 자동심기 Placeholder 메시지 설정(PlaceholderAPI)
# 스코어보드에 표시하는 용도임.

# stautoseed_time
Time: '%current_time%'

# stautoseed_status
Activated: '켜짐'
Deactivated: '꺼짐'